logLevel: warn
api: yes
apiAddress: 127.0.0.1:9997
rtmp: yes
rtmpAddress: 127.0.0.1:1935
rtsp: yes
rtspAddress: 127.0.0.1:8554
rtspTransports: [tcp]
hls: yes
hlsAddress: 127.0.0.1:8888
hlsVariant: lowLatency
hlsAlwaysRemux: yes
webrtc: no
srt: no
moq: no
paths:
  "~^live/stage-(1|2|3)$":
    source: publisher
